# coding=utf-8

API_KEY = 'YOUR_API_KEY'
API_SECRET = 'YOUR_API_SECRET'
TRADING_PAIR = 'BNBUSDT'
ANALYZE_WAIT = 5 # (seconds)
UPDATE_EXCHANGE_WAIT_TIME = 1.5 # (seconds)
CHECK_ORDER_WAIT_TIME = 1 # (seconds)
TRADER_WAIT_TIME = 2 # (seconds)
PARTIALLY_FILLED_WAIT_TIME = 180 # (seconds)
ORDER_WAIT_TIME = 60 # (seconds)
FEE = 0.1 # (percent)
SELL_PRICE_TICK_OFFSET = 10 # (ticks) 
BUY_PRICE_TICK_OFFSET = 10 # (ticks) 
BUY_MORE_PRICE_PERCENTAGE = 1.5 # (percent)
HULL_PERIOD = 33 # Hull moving average period
RSI_PERIOD = 14 # Relative Strength Index period
EMA_PERIOD = 99 # Exponential moving average period
BUY_MAX_RETRACEMENT_PERCENTAGE = 8.0 # (percent)
SELL_MAX_RETRACEMENT_PERCENTAGE = 20.0 # (percent)
IGNORE_SMALL_PEAK_PERCENTAGE = 5.0 # (percent)
RSI_OVERSOLD_PERCENTAGE = 30.0 # (percent)
MIN_MA_SPREAD = 0.4 # Minimum spread between two MA lines (percent)
EMA_TO_BUY_PRICE_PERCENTAGE = 0.32 # (percent)
PREFERRED_PROFIT = 1.2 # (percent)
QUANTITY_COEFFICIENT = 0.2
INITIAL_AMOUNT = 16.0 # Initial amount per trading thread
DIFF_TICKS = 10 # (ticks)
STOPLOSS_TRIGGER_PERCENTAGE = 1.0 # (percent)
STOPLOSS_PERCENTAGE = 0.4 # (percent)
IMMEDIATELY_STOPLOSS_PERCENTAGE = 2.0 # (percent)
